# docker-compose.yml

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway/src:/usr/app/src
    command: npm run start:dev
    environment:
      - PORT=3000

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    volumes:
      - ./user-service/src:/usr/app/src
    command: npm run start:dev
    environment:
      - PORT=3001

networks:
  app-network:
    driver: bridge
